# NumPy - Introduction
---
## Introduction:

Welcome to this introductory notebook on NumPy, a fundamental Python library for numerical computing. NumPy provides powerful tools for working with arrays and matrices, making it essential for scientific computing, data analysis, and machine learning tasks.

In this notebook, I'll cover the basics of NumPy, including array creation, manipulation, and basic mathematical operations.

I'll use various examples and exercises to help you understand the key concepts of NumPy and how to leverage its capabilities effectively.

### Table of Contents:

<li> <a href="#array-creation">Array Creation and Attributes</a> </li>
<li> <a href="#array-operations">Array Operations</a> </li>
<li> <a href="#indexing-slicing">Indexing and Slicing</a> </li>
<li> <a href="#array-manipulation">Array Manipulation</a> </li>
<li> <a href="#other-functions">Other Functions</a> </li>


In [1]:
# Import libraries
import numpy as np 
import matplotlib.pyplot as plt

A numpy array is similar to a list. It's usually fixed in size and each element is of the same type.

As numpy arrays contain data of the same type, we can use the attribute "dtype" to obtain the Data-type of the array’s elements.

<h2 id="array-creation">1. Array Creation and Attributes</h2>

#### Array Creation:

In [2]:
# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Attributes:

In [3]:
# Check the type of the array
print("1D Array:", type(arr_1d))
print("2D Array:", type(arr_2d))

1D Array: <class 'numpy.ndarray'>
2D Array: <class 'numpy.ndarray'>


We can use the attribute <code>ndim</code> to obtain the number of axes or dimensions referred to as the rank. 

In [4]:
# Show the numpy array dimensions
print("1D Array:", arr_1d.ndim)
print("2D Array:", arr_2d.ndim)

1D Array: 1
2D Array: 2


Attribute <code>shape</code> returns a tuple corresponding to the size or number of each dimension.

In [5]:
# Show the numpy array shape
print("1D Array:", arr_1d.shape)
print("2D Array:", arr_2d.shape)

1D Array: (5,)
2D Array: (3, 3)


The total number of elements in the array is given by the attribute <code>size</code>.

In [6]:
# Show the numpy array size
print("1D Array:", arr_1d.size)
print("2D Array:", arr_2d.size)

1D Array: 5
2D Array: 9


<h2 id="array-operations">2. Array Operations</h2>

In [7]:
# Define two 1D-arrays
arr1 = np.array([1, 2, 3])
print("Array 1: ", arr1)
arr2 = np.array([4, 5, 6])
print("Array 2: ", arr2)

# Addition
print("\nAddition:")
print(arr1 + arr2)

# Subtraction
print("\nSubtraction:")
print(arr2 - arr1)

# Multiplication
print("\nMultiplication:")
print(arr1 * arr2)

# Division
print("\nDivision:")
print(arr2 / arr1)

# Dot product
print("\nDot Product:")
print(np.dot(arr1, arr2))


Array 1:  [1 2 3]
Array 2:  [4 5 6]

Addition:
[5 7 9]

Subtraction:
[3 3 3]

Multiplication:
[ 4 10 18]

Division:
[4.  2.5 2. ]

Dot Product:
32


In [8]:
# Define two 2D-arrays
arr1 = np.array([[1, 4], [4, 1]])
print("Array 1: ", arr1)
arr2 = np.array([[2, 1], [1, 2]]) 
print("Array 2: ", arr2)

# Addition
print("\nAddition:")
print(arr1 + arr2)

# Subtraction
print("\nSubtraction:")
print(arr2 - arr1)

# Multiplication
print("\nMultiplication:")
print(arr1 * arr2)

# Division
print("\nDivision:")
print(arr2 / arr1)

# Dot product
print("\nDot Product:")
print(np.dot(arr1, arr2))

Array 1:  [[1 4]
 [4 1]]
Array 2:  [[2 1]
 [1 2]]

Addition:
[[3 5]
 [5 3]]

Subtraction:
[[ 1 -3]
 [-3  1]]

Multiplication:
[[2 4]
 [4 2]]

Division:
[[2.   0.25]
 [0.25 2.  ]]

Dot Product:
[[6 9]
 [9 6]]


#### Mathematical Functions:

In [9]:
# The value of pie
np.pi

3.141592653589793

In [10]:
print("Array:")
print(arr1)

# Sum
print("\nSum:")
print(arr1.sum())

# Min
print("\nMin:")
print(arr1.min())

# Max
print("\nMax:")
print(arr1.max())

# Mean
print("\nMean:")
print(arr1.mean())

# Standard Deviation
print("\nStandard Deviation:")
print(arr1.std())

Array:
[[1 4]
 [4 1]]

Sum:
10

Min:
1

Max:
4

Mean:
2.5

Standard Deviation:
1.5


In [11]:
print("Array:")
print(arr1)

# Square root
print("\nSquare root:")
print(np.sqrt(arr1))

# Exponential
print("\nExponential:")
print(np.exp(arr1))

# Trigonometric functions
print("\nSin:")
print(np.sin(arr1))
print("Cos:")
print(np.cos(arr1))

Array:
[[1 4]
 [4 1]]

Square root:
[[1. 2.]
 [2. 1.]]

Exponential:
[[ 2.71828183 54.59815003]
 [54.59815003  2.71828183]]

Sin:
[[ 0.84147098 -0.7568025 ]
 [-0.7568025   0.84147098]]
Cos:
[[ 0.54030231 -0.65364362]
 [-0.65364362  0.54030231]]


<h2 id="indexing-slicing">3. Indexing and Slicing</h2>

In [12]:
# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Indexing:

In [13]:
# Access elements by index 1D-array
print("Array:\n", arr_1d)
print("First element:", arr_1d[0])
print("Last element:", arr_1d[-1])

Array:
 [1 2 3 4 5]
First element: 1
Last element: 5


In [14]:
# Access elements by index 2D-array
print("Array:\n", arr_2d)
print("First row:", arr_2d[0])
print("Last row:", arr_2d[-1])
print("First column:", arr_2d[:, 0])
print("Last column:", arr_2d[:, -1])

# Acces the element on an specific row and column
print("Element in an specific (row=1, column=3):", arr_2d[0][2])
print("Element in an specific (row=2, column=2):", arr_2d[1, 1])

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row: [1 2 3]
Last row: [7 8 9]
First column: [1 4 7]
Last column: [3 6 9]
Element in an specific (row=1, column=3): 3
Element in an specific (row=2, column=2): 5


#### Slicing:

In [15]:
# Slicing the numpy 1D-array
print("Array:\n", arr_1d)
print("Slicing (row 2 to row 4): ",arr_1d[1:4])
print("Slicing (row 2 to row 4): ",arr_1d[1:4])

Array:
 [1 2 3 4 5]
Slicing (row 2 to row 4):  [2 3 4]
Slicing (row 2 to row 4):  [2 3 4]


In [16]:
# Slicing the numpy 2D-array
print("Array:\n", arr_2d)
print("Slicing in a specific row and columns (row=1, col=1 to 2): ",arr_2d[0][:2])
print("Slicing in a specific row and columns (row=2 to 3, col=2): ",arr_2d[1:3, 2])


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Slicing in a specific row and columns (row=1, col=1 to 2):  [1 2]
Slicing in a specific row and columns (row=2 to 3, col=2):  [6 9]


<h2 id="array-manipulation">4. Array Manipulation</h2>


Reshaping arrays: ```.reshape(rows, cols)```

In [17]:
# Reshape array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print("Original Array:")
print(arr)
print("\nReshaped Array:")
print(reshaped_arr)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]


Concatenation: ```.concatenate() ```

In [18]:
# Concatenate arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated Array:")
print(concatenated_arr)

Concatenated Array:
[1 2 3 4 5 6]


Assign Value

In [19]:
# Assign values in 1D
print("1D Array:")
print(arr_1d)

# Assigning a single value
arr_1d[0] = 10  
print("\nUpdated 1D Array:")
print(arr_1d)

# Assigning multiple values using slicing
arr_1d[1:3] = [20, 30]  
print("\nUpdated 1D Array after slicing:")
print(arr_1d)


1D Array:
[1 2 3 4 5]

Updated 1D Array:
[10  2  3  4  5]

Updated 1D Array after slicing:
[10 20 30  4  5]


In [20]:
# Assign values in 2D
print("\n2D Array:")
print(arr_2d)

# Assigning a single value
arr_2d[0, 0] = 10  
print("\nUpdated 2D Array:")
print(arr_2d)

# Assigning values to a subarray
arr_2d[1:, 1:] = np.array([[20, 30], [50, 60]])  
print("\nUpdated 2D Array after slicing:")
print(arr_2d)


2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Updated 2D Array:
[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]

Updated 2D Array after slicing:
[[10  2  3]
 [ 4 20 30]
 [ 7 50 60]]


#### Element-wise comparison and Conditional indexing:
NumPy allows you to perform element-wise comparisons between arrays using standard comparison operators such as ```<```, ```<=```, ```==```, ```!=```, ```>```, and ```>=```.

| Function      | Description               |
|---------------|---------------------------|
| np.equal()    | Element-wise equality     |
| np.not_equal()| Element-wise inequality   |
| np.less()     | Element-wise less than    |
| np.less_equal()| Element-wise less than or equal to |
| np.greater()  | Element-wise greater than |
| np.greater_equal()| Element-wise greater than or equal to |
| np.logical_and()| Element-wise logical AND |
| np.logical_or()| Element-wise logical OR  |
| np.logical_not()| Element-wise logical NOT |
| np.isin()     | Element-wise membership test |
| np.isnan()    | Element-wise is NaN       |
| np.isinf()    | Element-wise is infinity  |
| np.isfinite()| Element-wise is finite     |


In [21]:
# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# Perform element-wise comparison
print("\nElement-wise comparison (greater than 2):")
print(arr_1d > 2)

# Perform conditional indexing
print("\nElements greater than 2:")
print(arr_1d[arr_1d > 2])

print("\nEven elements:")
print(arr_1d [arr_1d  % 2 == 0])

# Conditional assignment
arr_1d[arr_1d > 3] = 10
print("\nModified array:")
print(arr_1d)

1D Array:
[1 2 3 4 5]

Element-wise comparison (greater than 2):
[False False  True  True  True]

Elements greater than 2:
[3 4 5]

Even elements:
[2 4]

Modified array:
[ 1  2  3 10 10]


In [22]:
# Create a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

# Element-wise greater than
print("\nElement-wise greater than (greater than 3):")
print(np.greater(arr_1d, 3))

# Element-wise greater than or equal to
print("\nElement-wise greater than or equal to (greater than or equal to 3):")
print(np.greater_equal(arr_1d, 3))

# Element-wise logical AND
print("\nElement-wise logical AND (greater than 2 and less than 4):")
print(np.logical_and(arr_1d > 2, arr_1d < 4))

# Element-wise logical OR
print("\nElement-wise logical OR (less than 2 or greater than 4):")
print(np.logical_or(arr_1d < 2, arr_1d > 4))

# Element-wise logical NOT
print("\nElement-wise logical NOT (not equal to 3):")
print(np.logical_not(np.equal(arr_1d, 3)))

# Element-wise membership test
print("\nElement-wise membership test (isin):")
print(np.isin(arr_1d, [2, 4, 6]))

# Element-wise is NaN (Not a Number)
arr_nan = np.array([1, np.nan, 3, np.nan, 5])
print("\nElement-wise is NaN:")
print(np.isnan(arr_nan))

1D Array:
[1 2 3 4 5]

Element-wise greater than (greater than 3):
[False False False  True  True]

Element-wise greater than or equal to (greater than or equal to 3):
[False False  True  True  True]

Element-wise logical AND (greater than 2 and less than 4):
[False False  True False False]

Element-wise logical OR (less than 2 or greater than 4):
[ True False False False  True]

Element-wise logical NOT (not equal to 3):
[ True  True False  True  True]

Element-wise membership test (isin):
[False  True False  True False]

Element-wise is NaN:
[False  True False  True False]


In [23]:
# Create a 2D NumPy array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

# Perform element-wise comparison
print("\nElement-wise comparison (greater than 3):")
print(arr_2d > 3)

# Perform conditional indexing
print("\nElements greater than 3:")
print(arr_2d[arr_2d > 3])

print("\nEven elements:")
print(arr_2d [arr_2d  % 2 == 0])

# Conditional assignment
arr_2d[arr_2d > 3] = 10
print("\nModified array:")
print(arr_2d)



2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element-wise comparison (greater than 3):
[[False False False]
 [ True  True  True]
 [ True  True  True]]

Elements greater than 3:
[4 5 6 7 8 9]

Even elements:
[2 4 6 8]

Modified array:
[[ 1  2  3]
 [10 10 10]
 [10 10 10]]


<h2 id="other-functions">5. Other Functions</h2>

NumPy provides several useful functions for array creation, and ```np.linspace()``` is one of them. This function is particularly handy for creating evenly spaced numbers over a specified range.

```np.linspace(start, stop, num)```

The ```np.linspace()``` function generates evenly spaced numbers over a specified interval. It takes three arguments: start, stop, and num, where:

- start: The starting value of the sequence.
- stop: The end value of the sequence.
- num: The number of samples to generate.

In [24]:
# Generate a numpy array
arr = np.linspace(-1, 1, 5)
print("Array created using np.linspace():")
print(arr)

Array created using np.linspace():
[-1.  -0.5  0.   0.5  1. ]


In [25]:
# Generate a 2D array with 3 rows and 4 columns, containing evenly spaced numbers between 0 and 1
arr_2d = np.linspace(0, 1, num=3*4).reshape(3, 4)
print("2D Array created using np.linspace():")
print(arr_2d)

2D Array created using np.linspace():
[[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]


The ```np.zeros()``` function creates an array filled with zeros. It takes the shape of the array as an argument.

In [26]:
# Create a 2x3 array filled with zeros
zeros_array = np.zeros((2, 3))
print("Array filled with zeros:")
print(zeros_array)

Array filled with zeros:
[[0. 0. 0.]
 [0. 0. 0.]]


Similar to ```np.zeros()```, the ```np.ones()``` function creates an array filled with ones.

In [27]:
# Create a 3x2 array filled with ones
ones_array = np.ones((3, 2))
print("Array filled with ones:")
print(ones_array)

Array filled with ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


The ```np.eye()``` function generates an identity matrix of the specified size.

In [28]:
# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\nIdentity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The ```np.split()``` function splits an array into multiple sub-arrays along a specified axis.

In [29]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Array:")
print(arr)

# Split the array into three equal-sized sub-arrays
sub_arrays = np.split(arr, 3)
print("\nSplit 1D array into sub-arrays:")
print(sub_arrays)

Array:
[1 2 3 4 5 6]

Split 1D array into sub-arrays:
[array([1, 2]), array([3, 4]), array([5, 6])]


```np.hsplit()``` and ```np.vsplit()```

If you're working with 2D arrays, you can use ```np.hsplit()``` and ```np.vsplit()``` to split the array horizontally (along columns) and vertically (along rows), respectively.

In [30]:
# Create a 2D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:")
print(arr_2d)

# Split the array horizontally into sub-arrays
horizontal_split = np.hsplit(arr_2d, 3)
print("\nHorizontal split:")
print(horizontal_split)

# Split the array vertically into sub-arrays
vertical_split = np.vsplit(arr_2d, 3)
print("\nVertical split:")
print(vertical_split)

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal split:
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

Vertical split:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


The ```np.stack()``` function stacks arrays along a new axis. It takes a sequence of arrays and stacks them along a new axis.

In [31]:
# Create two 1D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stack the arrays along a new axis (vertical stacking)
stacked_array = np.stack((arr1, arr2))
print("\nStacked array:")
print(stacked_array)


Stacked array:
[[1 2 3]
 [4 5 6]]


```np.vstack()``` and ```np.hstack()```

If you want to vertically stack or horizontally stack arrays, you can use ```np.vstack()``` and ```np.hstack()```.

In [32]:
# Vertically stack two arrays
vertical_stack = np.vstack((arr1, arr2))
print("\nVertically stacked array:")
print(vertical_stack)

# Horizontally stack two arrays
horizontal_stack = np.hstack((arr1, arr2))
print("\nHorizontally stacked array:")
print(horizontal_stack)


Vertically stacked array:
[[1 2 3]
 [4 5 6]]

Horizontally stacked array:
[1 2 3 4 5 6]
